routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/register', 'Auth\RegisterController@abort')->name('register');
Route::post('/register', 'Auth\RegisterController@abort')->name('register.post');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/digital', 'HomeController@digital')->name('digital');
Route::get('/traditional', 'HomeController@traditional')->name('traditional');
Route::get('/design', 'HomeController@design')->name('design');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::post('/contact', 'HomeController@processContact')->name('process.contact');

Route::get('/thanks', 'HomeController@thanks')->name('thanks');

Route::get('/adventure', 'SubPageController@adventure')->name('adventure');
Route::get('/favorites', 'SubPageController@favorites')->name('favorites');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {
	Route::get('/', 'HomeController@dashboard')->name('dashboard');

	Route::post('images/order', 'ImageController@updateOrder');
	Route::resource('images', 'ImageController');

	Route::resource('image-types', 'ImageTypeController');

	Route::resource('pages', 'PageController');
	Route::post('pages/attach', 'PageController@asyncAttach');
	Route::post('pages/detach', 'PageController@asyncDetach');

	Route::resource('users', 'UserController');
});

app/Http/Controllers/Admin/ImageTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\ImageType;

class ImageTypeController extends Controller
{
	/**
	 * Show a listing of image types.
	 *
	 * @return \Illuminate\Http\Response
	 */
    public function index()
    {
    	$data['types'] = ImageType::orderBy('name')->get();

    	return view('admin.image-types.index', $data);
    }

    /**
     * Create a new image type.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	return $this->edit(new ImageType());
    }

    /**
     * Store a newly created image type.
     *
     * @param  \Illuminate\Https\Request $request
     * @return \Illuminate\Https\Response
     */
    public function store(Request $request)
    {
    	return $this->update($request, new ImageType());
    }

    /**
     * Show the form for editing or creating an image type.
     *
     * @param  \App\Models\ImageType $imageType
     * @return \Illuminate\Http\Response
     */
    public function edit(ImageType $imageType)
    {
    	$this->authorize('update', $imageType);

    	$data['type'] = $imageType;

    	return view('admin.image-types.edit', $data);
    }

    /**
     * Update an image type in storage.
     *
     * @param  \Illuminate\Http\Request   $request
     * @param  \App\Models\ImageType $imageType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ImageType $imageType)
    {
    	$this->authorize('update', $imageType);

    	$this->validate($request, [
    		'name' => 'required|string|max:255',
    		'slug' => 'required|string|unique:image_types,slug,' . $imageType->id,
    	]);

    	$imageType->name = $request->input('name');
    	$imageType->slug = $request->input('slug');

    	if ($imageType->save()) {
    		return redirect(route('admin.image-types.edit', $imageType))->with('success', 'Image type has been saved.');
    	} else {
    		return redirect(route('admin.image-types.edit', $imageType))->with('danger', 'Something went wrong, please try again.');
    	}
    }

    /**
     * Destroy the specified image type.
     *
     * @param  \App\Models\ImageType $imageType
     * @return \Illuminate\Http\Response
     */
    public function destroy(ImageType $imageType)
    {
    	$this->authorize('destroy', $imageType);

    	if ($imageType->images()->count()) {
    		return redirect(route('admin.image-types.index'))->with('danger', $imageType->images()->count() . ' image(s) are attached to this type, change the image types first.');
    	}

    	if ($imageType->delete()) {
    		return redirect(route('admin.image-types.index'))->with('success', 'Image type was deleted.');
    	} else {
    		return redirect(route('admin.image-types.index'))->with('danger', 'Something went wrong, please try again.');
    	}
    }
}

resources/views/admin/image-types/edit.blade.php
@extends ('layouts.admin')

@section ('content')
	<div class="image-type-edit-wrapper">
		@if ($type->id)
			<h1>Edit {{ $type->name }}</h1>
		@else
			<h1>Create New Image Type</h1>
		@endif

		<form class="basic-form" role="form" action="/admin/image-types{{ $type->id ? '/' . $type->id : '' }}" method="POST" autocomplete="force-no">
			@csrf

			@if ($type->id)
				@method('PATCH')
			@endif

			@include ('partials.alerts')

			<div class="form-group">
				<label for="name">Name</label>

				<input id="name" class="form-control" type="text" name="name" value="{{ $type->name ?? old('name') }}">
			</div>

			<div class="form-group">
				<label for="slug">Slug</label>

				<input id="slug" class="form-control" type="text" name="slug" value="{{ $type->slug ?? old('slug') }}">
			</div>

            <button class="btn btn-primary" type="submit">Submit/Update Image Type</button>
		</form>
	</div>
@endsection

resources/views/admin/image-types/index.blade.php
@extends ('layouts.admin')

@section ('content')
	<div class="image-types-index-wrapper">
		<div class="d-flex vertical-align justify-content-between">
			<h1>Image Types</h1>

			<a href="{{ route('admin.image-types.create') }}">
				<button class="btn btn-teal">
					<i class="fa fa-plus"></i> New Image Type
				</button>
			</a>
		</div>

		@include ('partials.alerts')

		<table class="table">
			<thead>
				<th>Name</th>

				<th>Image Count</th>

				<th>Actions</th>

				<th>&nbsp</th>
			</thead>

			<tbody>
				@foreach ($types as $type)
					<tr>
						<td>
							<a href="{{ route('admin.image-types.edit', $type) }}">{{ $type->name }}</a>
						</td>

						<td>{{ $type->images()->count() }}</td>

						<td>
							<a href="{{ route('admin.image-types.edit', $type) }}">
								<i title="Edit" class="fa fa-edit"></i>
							</a>
						</td>

						<td>
							<form action="{{ route('admin.image-types.destroy', $type) }}" method="POST" onsubmit="if(!confirm('Are you sure? This is permanent.')) return false">
								@csrf @method('DELETE')

								<button type="submit" style="background-color: white; color: red;">
									<i title="Delete" class="fa fa-trash"></i>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
	</div>
@endsection