routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/register', 'Auth\RegisterController@abort')->name('register');
Route::post('/register', 'Auth\RegisterController@abort')->name('register.post');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/digital', 'HomeController@digital')->name('digital');
Route::get('/traditional', 'HomeController@traditional')->name('traditional');
Route::get('/design', 'HomeController@design')->name('design');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::post('/contact', 'HomeController@processContact')->name('process.contact');

Route::get('/thanks', 'HomeController@thanks')->name('thanks');

Route::get('/adventure', 'SubPageController@adventure')->name('adventure');
Route::get('/favorites', 'SubPageController@favorites')->name('favorites');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {
	Route::get('/', 'HomeController@dashboard')->name('dashboard');

	Route::post('images/order', 'ImageController@updateOrder');
	Route::resource('images', 'ImageController');

	Route::resource('image-types', 'ImageTypeController');

	Route::resource('pages', 'PageController');
	Route::post('pages/attach', 'PageController@asyncAttach');
	Route::post('pages/detach', 'PageController@asyncDetach');

	Route::resource('users', 'UserController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Return the user's full name.
     *
     * @return string
     */
    public function getNameAttribute()
    {
        $name = '';

        if ($this->first_name && $this->last_name) {
            $name = $this->first_name . ' ' . $this->last_name;
        }

        return $name;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\User;

class UserController extends Controller
{
	/**
	 * Show the index of users.
	 *
	 * @return \Illuminate\Http\Response
	 */
    public function index()
    {
    	$data['users'] = User::orderBy('last_name')->get();

    	return view('admin.users.index', $data);
    }

    /**
     * Show the form for creating a new user.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	return $this->edit(new User());
    }

    /**
     * Store a newly created user.
     *
     * @param  \Illuminate\Http\Request $request [description]
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    	return $this->update($request, new User());
    }

    /**
     * Show the form for editing the specified user.
     *
     * @param  App\Models\User   $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
    	$this->authorize('update', $user);

    	$data['user'] = $user;

    	return view('admin.users.edit', $data);
    }

    /**
     * Update the user in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\User    		$user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
    	$this->authorize('update', $user);

        $rules = [
            'first_name' => 'required|max:255|string',
            'last_name' => 'required|max:255|string',
            'email' => 'required|email|max:255|unique:users,email,' . $user->id,
        ];

        if ($user->id) {
            $rules['password'] = 'nullable|min:6|confirmed';
        } else {
            $rules['password'] = 'required|min:6|confirmed';
        }

    	$this->validate($request, $rules);

    	$user->first_name = $request->input('first_name');
    	$user->last_name = $request->input('last_name');
    	$user->email = $request->input('email');

    	if ($request->filled('password')) $user->password = bcrypt($request->input('password'));

    	$saved = $user->save();

    	if ($saved) {
    		return redirect(route('admin.users.edit', $user))->with('success', 'User was saved.');
    	} else {
    		return redirect(route('admin.users.edit', $user))->with('danger', 'Something went wrong.');
    	}
    }

    /**
     * Destroy the specified user.
     *
     * @param  \App\Models\User   $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
    	$this->authorize('destroy', $user);

    	if ($user->delete()) {
    		return redirect(route('admin.users.index'))->with('success', 'User was deleted.');
    	} else {
    		return redirect(route('admin.users.index'))->with('danger', 'Something went wrong.');
    	}
    }
}

resources/views/admin/users/edit.blade.php
@extends ('layouts.admin')

@section ('content')
	<div class="user-edit-wrapper">
		@if ($user->id)
			<h1>Edit {{ $user->name }}</h1>
		@else
			<h1>Create New User</h1>
		@endif

		<form class="basic-form" role="form" action="/admin/users{{ $user->id ? '/' . $user->id : '' }}" method="POST" autocomplete="force-no">
			@csrf

			@if ($user->id)
				@method('PATCH')
			@endif

			@include ('partials.alerts')

			<div class="form-group form-row">
				<div class="col">
					<label for="first_name">First Name</label>

					<input class="form-control" type="text" name="first_name" value="{{ $user->first_name ?? old('first_name') }}">
				</div>

				<div class="col">
					<label for="last_name">Last Name</label>

					<input class="form-control" type="text" name="last_name" value="{{ $user->last_name ?? old('last_name') }}">
				</div>
			</div>

			<div class="form-group">
				<label for="email">Email</label>

				<input class="form-control" type="email" name="email" value="{{ $user->email ?? old('email') }}">
			</div>

			<div class="form-group">
                <label for="password">User Password:</label>

                <input class="form-control" type="password" name="password">
            </div>

            <div class="form-group">
                <label for="password">Confirm Password:</label>

                <input class="form-control" type="password" name="password_confirmation">
            </div>

            <button class="btn btn-primary" type="submit">Submit/Update User</button>
		</form>
	</div>
@endsection

resources/views/admin/users/index.blade.php
@extends ('layouts.admin')

@section ('content')
	<div class="user-index-wrapper">
		<div class="d-flex vertical-align justify-content-between">
			<h1>Users</h1>

			<a href="{{ route('admin.users.create') }}">
				<button class="btn btn-teal">
					<i class="fa fa-plus"></i> New User
				</button>
			</a>
		</div>

		@include ('partials.alerts')

		<table class="table">
			<thead>
				<th>Name</th>

				<th>Email</th>

				<th>Actions</th>

				<th>&nbsp</th>
			</thead>

			<tbody>
				@foreach ($users as $user)
					<tr>
						<td>
							<a href="{{ route('admin.users.edit', $user) }}">{{ $user->first_name }} {{ $user->last_name }}</a>
						</td>

						<td>{{ $user->email }}</td>

						<td>
							<a href="{{ route('admin.users.edit', $user) }}">
								<i title="Edit" class="fa fa-edit"></i>
							</a>
						</td>

						<td>
							<form action="{{ route('admin.users.destroy', $user) }}" method="POST" onsubmit="if(!confirm('Are you sure? This is permanent.')) return false">
								@csrf @method('DELETE')

								<button type="submit" style="background-color: white; color: red;">
									<i title="Delete" class="fa fa-trash"></i>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
	</div>
@endsection