routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/register', 'Auth\RegisterController@abort')->name('register');
Route::post('/register', 'Auth\RegisterController@abort')->name('register.post');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/digital', 'HomeController@digital')->name('digital');
Route::get('/traditional', 'HomeController@traditional')->name('traditional');
Route::get('/design', 'HomeController@design')->name('design');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::post('/contact', 'HomeController@processContact')->name('process.contact');

Route::get('/thanks', 'HomeController@thanks')->name('thanks');

Route::get('/adventure', 'SubPageController@adventure')->name('adventure');
Route::get('/favorites', 'SubPageController@favorites')->name('favorites');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {
	Route::get('/', 'HomeController@dashboard')->name('dashboard');

	Route::post('images/order', 'ImageController@updateOrder');
	Route::resource('images', 'ImageController');

	Route::resource('image-types', 'ImageTypeController');

	Route::resource('pages', 'PageController');
	Route::post('pages/attach', 'PageController@asyncAttach');
	Route::post('pages/detach', 'PageController@asyncDetach');

	Route::resource('users', 'UserController');
});

resources/views/admin/pages/edit.blade.php
@extends ('layouts.admin')

@section ('content')
	<div class="page-edit-wrapper">
		<div class="header clearfix">
			<h1 class="pull-left">@if ($page->id) Edit @else Create @endif Page</h1>

			<a href="{{ route('admin.pages.create') }}">
				<button class="btn btn-teal pull-right">
					<i class="fa fa-plus"></i>
				</button>
			</a>
		</div>

		<form class="basic-form" role="form" action="/admin/pages{{ $page->id ? '/' . $page->id : '' }}" method="POST" autocomplete="force-no" enctype="multipart/form-data">
			@csrf

			@if ($page->id) 
				@method ('PATCH')
			@endif

			@include ('partials.alerts')

			<div class="form-group">
				<label for="synopsis">Synopsis</label>

				<input id="synopsis" class="form-control" type="text" name="synopsis" value="{{ old('synopsis') ?? $page->synopsis }}">
			</div>

			<div class="form-group">
				<label for="text">Page Content</label>

				<tinymce id="text" name="text" value="{{ old('text') ?? $page->text }}"></tinymce>
			</div>

			<div class="form-group">
				<label for="image">Select Image (Optional)</label>

				<input type="file" name="image" class="form-control-file" id="image">
			</div>

			@if ($page->image_url)
				<div class="form-group">
					<label>Current Image</label>

					<img src="{{ $page->image_url }}" class="img-fluid">
				</div>

				<div class="form-check">
					<input class="form-check-input" type="checkbox" name="remove_image" id="remive_image">

					<label class="form-check-label" for="remove_image">Remove Image</label>
				</div>
			@endif

			<div class="form-group">
				<button type="submit" class="btn btn-teal">Submit</button>
			</div>
		</form>

		<hr>

		<page-attacher :page="{{ $page }}" :available-pages="{{ json_encode($availablePages) }}"></page-attacher>
	</div>
@endsection

resources/views/admin/pages/index.blade.php
@extends ('layouts.admin')

@section ('content')
	<div class="page-index-wrapper">
		<div class="header clearfix">
			<h1 class="pull-left">Choose Your Own Pages</h1>

			<a href="{{ route('admin.pages.create') }}">
				<button class="btn btn-teal pull-right">
					<i class="fa fa-plus"></i>
				</button>
			</a>
		</div>

		<div class="mt-5">
			<form class="form">
				<div class="row">
					<div class="col">
						<input class="form-control" name="search" type="text" value="{{ request()->get('search') }}" placeholder="Search by synopsis">
					</div>

					<div class="col">
						<button type="submit" class="btn btn-teal">
							<i class="fa fa-search"></i>
						</button>
					</div>
				</div>
			</form>
		</div>

		<div class="mt-5">
			@include ('partials.alerts')
			
			@if ($pages->count())
				<table class="table">
					<thead>
						<tr>
							<th>ID</th>

							<th>Synopsis</th>

							<th>Created</th>

							<th>Delete</th>
						</tr>
					</thead>

					<tbody>
						@foreach ($pages as $page)
							<tr>
								<td>{{ $page->id }}</td>

								<td>
									<a href="{{ route('admin.pages.edit', $page) }}">{{ $page->synopsis }}</a>
								</td>

								<td>{{ date('d-m-Y', strtotime($page->created_at)) }}</td>

								<td>
									<form action="{{ route('admin.pages.destroy', $page) }}" method="POST" onsubmit="if (!confirmed('Are you sure?')) return false;">
										@csrf @method('DELETE')

										<button class="btn" type="submit">
											<i class="fa fa-trash-o"></i>
										</button>
									</form>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			@else
				<p>No pages match your criteria.</p>
			@endif

			@if ($pages->count())
				<div class="pagination-wrapper">
					{{ $pages->appends(request()->all())->links() }}
				</div>
			@endif
		</div>
	</div>
@endsection